kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-pv
  namespace: nginx
  labels:
    app: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/nginx