kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-deployment
  namespace: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio
        image: ankitrj3/portfolio
        ports:
        - containerPort: 3000